[package]
name = "charting"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
console = "0.16.1"
rgb = "0.8.52"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
